### ISSUE TITLE
反编译报错

### ISSUE THREAD

**Issue by miaomiaojianglove** [one066/Exe-decompiling#1]
You can now use a python decompiler on the pyc files within the extracted directory
# uncompyle6 version 3.7.4
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
# Embedded file name: Class_And_Movies_Down_BYYG.py
# Compiled at: 1995-09-28 00:18:56
# Size of source mod 2**32: 272 bytes
import hashlib, base64, re, requests, json, os, queue, threading, time, hmac, multiprocessing, subprocess, wmi, pythoncom, sys, html, xmltodict, shutil, zlib, gzip, win32gui, win32process, toml, rsa, socks
from Crypto.Cipher import AES, PKCS1_OAEP, PKCS1_v1_5
from Crypto.Hash import CMAC
from Crypto.PublicKey import RSA
from Crypto.Util.Padding import pad, unpad
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization, hashes
from cryptography.hazmat.primitives.asymmetric import padding
from urllib import request, parse
from PIL import Image, ImageDraw, ImageFont
from ctypes import c_uint, c_int
requests.packages.urllib3.disable_warnings()
import cto51, mukewang, tengxunketang, zhongguodaxue, wangyiyunketang, csdn, zhonggongwangxiao, tulingxueyuan, zhonghuakuaijiwangxiao, quanguotezhongshebeijianyanjiancerenyuan, wanmendaxue, pltccinteriors, kukewangxiao, xuetangzaixian, huanqiuwangxiao, huke88, yiihuu, shejiqixiangtai, cctv, zxw51, gupaoxueyuan, mangguotv, youku, tengxunshipin, iqiyi, bilibili, pptv, xigua, migushipin, ddrk, iyamusic, linetv, viki, hamivideo, nfmovies, epangml, kktv, u5yingshi, mpdtom3u8, pywvdecrypt, huanxishouying, pili, appletv, camdmain, traceback, publicfun

def main():
    camdmain.main()

if __name__ == '__main__':
    multiprocessing.freeze_support()
    try:
        main()
    except:
        print('程序运行中出现意料之外的错误，可能是你的操作不正确导致的')
        input(traceback.format_exc())
# okay decompiling Class_And_Movies_Down_BYYG.pyc

C:\Users\Administrator\Downloads\Exe-decompiling-main>

**Comment by one066** [comment]
What do you mean，l don`t understand
